var GAME_LEVELS = [
  ["  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                           x                                              x  ",
   "  x                           x                                   xxx     xxxx  ",
   "  x                           x                                 x            x  ",
   "  x                           x                                              x  ",
   "  x                           x                                      Z     o x  ",
   "  x                           x                    xx      xx        xxxxxxxxx  ",
   "  x  x        x  o #x               o o                ^^        X!!!X       x  ",
   "  x  x        xxxxxxx                 H                          XX!XX       x  ",
   "  x  xx                            xxxxx                          XXX        x  ",
   "  xo a                              X                                       xx  ",
   "  xo a                                    o o                                x  ",
   "  xxxx                  o                                                    x  ",
   "  x                           x          xxxxx                             o x  ",
   "  x          xxxx      I                                                     x  ",
   "  x       @           ~x            x    ~  ooo     ~x           xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              X     X                X     X                    ",
   "                              x!!!!!x                x!!!!!x                    ",
   "                              x!!!!!x                x!!!!!x                    ",
   "                              xxxxxxx                xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                              x              xxx  ",
   "                                                                                              x              xxx  ",
   "                                                           xxxxxxxxxxxxxxxxx                  x     #   #    xxx  ",
   "                                                 xxx       xx*xx*xx*xx*xx*xx                  x                x  ",
   "                     x^^^x                       x!x       xx xx xx xx xx xx                  x   o   o   o    x  ",
   "                     x^^^x                       x!x       xx xx xx xx xx xx                  xxxxxxxxxxxxxxx  x  ",
   "                     x^^^x                       x!x          xx xx xx xx xx                                   x  ",
   "                     xx*xx                       xvx                                     xx~                   x  ",
   "                                                              o  o  o  o         xxx      xxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                            xxxxxxxxxxxxxxxxx             x                       ",
   "  o                            o                               xxxxxxxx^^^^^^^^^^^^^^^^^^^^                       ",
   "xxxxx     xxxx     x        xxxxx              xxxxxxxxxxx           x                                            ",
   "    ^     x  x     x                   ^^^^x   x     x!!!x           x                                            ",
   "          xxxx    xx                   x!!!xx  x     x!!!x   xxxxx   x                                            ",
   "                   xxxxxxx             x!!!x   x     xx^^x           x                                            ",
   "    x ~    o      ~x                   xxvxx   x^^^^^x              xx                                            ",
   "    xxxxxxxxxxxxxxxx                           x                     x                                            ",
   "          ^                                   xx             o  o    x                                            ",
   "          ^                      o             x             x^^x    x                                            ",
   "          #                                    x    xx               x                                            ",
   "     @                       xxxx^^^xx         x     xxxx            x                                            ",
   "^   xxx      xxxxxxxxxxx        xxxxxxx    xxxxx     x        o~x    x                                            ",
   "    xxx      x         x       xxxxxxx!!!!!!!!!x     x      xxxxx^^^^x                                            ",
   "    xxx      x         x!!!!!!xxxxxxxxx!!!!!!!!xx    x!!!!!!!!x                                                   ",
   "    xxx      x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx                                                   ",
   "   ^xxx    xxx         x!!!!!x   o                  xx!!!!!!xx                                                    ",
   "    xxx      x         x!!!!!x                 o   xx!!!!!!xx                                                     ",
   "             x         x!!!!!xx~     ~xxxxxxxxxxxxxx!!!!!!xx                                                      ",
   "~  o     o  ~x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                       ",
   "xxxxxxxxxxxxxx         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "                         xx#xx xx xx xx xx xx#xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx           ",
   "                         xx xx#xx xx xx xx#xx xx#xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx           ",
   "                                 #     #           #                                                          ",
   "                         o  o  o  o #o  o  o  o  o                                                            ",
   "                                                                                                              ",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         ",
   "                                                                           x                                  ",
   "                                                                           x                           xxx^^^^",
   "                                                                           x                                  ",
   "                                                                           x                                  ",
   "                                                                           x                  xxxxxx          ",
   "                                                                           x         xxxx                     ",
   "                                                                           x ^  ^                             ",
   "                                                                             ^  ^                             ",
   "                                                                         ^   ^  ^                             ",
   "                                                                  #      #   ^  ^                             ",
   "                                                                                                              ",
   "                                          x~      x   x  o  ~x                 j                              ",
   "                               ^xx     ^  xxxxxxxxx   xxxxxxxx     xxxxx   xxxxx                              ",
   "                               ^       ^                       #                                              ",
   "                               ^       ^                       ^^^^      ^                                    ",
   "                               ^       ^                                                                      ",
   "                               ^     xx^                                                                      ",
   "                               ^       ^                                                                      ",
   "                               ^       ^                                                                      ",
   "                               ^xx     ^                                                                      ",
   "xxxxxxxxxxxxxxx                ^       ^                                                                      ",
   "x       #     x                ^       ^                                                                      ",
   "x             x                ^     xx^                                                                      ",
   "xZ            x                                                                                               ",
   "xxx          Jx                                                                                               ",
   "x         xxxxx               @ o                                                                             ",
   "x                             xxxx                                                                            ",
   "x               ~x                                                                                            ",
   "xxxxxxxxxxxxxxxxxxxxxxx                                                                                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        x      ~x     o                                                       ",
   "                           xx      xx   xxxxxxxxx    xx                                                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
